#! /usr/bin/env python
# encoding: utf-8

obj = bld.new_task_gen(
    features = 'cc cprogram',
    packages = 'gtk+-2.0 gstreamer-0.10 goocanvas libxml-2.0',
    target = 'plugster',
    uselib = 'GLIB GTK GSTREAMER GOOCANVAS PANGO XML'
    )

obj.find_sources_in_dirs('.') # take the sources in the current folder

